---
title: "hw01_gapminder"
author: "Cassandra"
date: '2017-09-14'
output: github_document
---
```{r Exploration}
library(gapminder)
library(tidyverse)
class(gapminder)
head(gapminder)
tail(gapminder)
names(gapminder)
ncol(gapminder)
length(gapminder)
dim(gapminder)
nrow(gapminder)
summary(gapminder)
```

```{r Plots of data}
plot(lifeExp ~ year, gapminder)
plot(lifeExp ~ gdpPercap, gapminder)
plot(lifeExp ~ log(gdpPercap), gapminder)
```

```{r More exploration on data}
hist(gapminder$lifeExp)
summary(gapminder$year)
table(gapminder$year)
class(gapminder$continent)
summary(gapminder$continent)
levels(gapminder$continent)
nlevels(gapminder$continent)
str(gapminder$continent)
table(gapminder$continent)
barplot(table(gapminder$continent))
```

```{r Use ggplot to plot gapminder data}
p <- ggplot(filter(gapminder, continent != "Oceania"),
            aes(x = gdpPercap, y = lifeExp)) # just initializes
p <- p + scale_x_log10() # log the x axis the right way
p + geom_point() # scatterplot
p + geom_point(aes(color = continent)) # map continent to color
p + geom_point(alpha = (1/3), size = 3) + geom_smooth(lwd = 3, se = FALSE)
p + geom_point(alpha = (1/3), size = 3) + facet_wrap(~ continent) +
  geom_smooth(lwd = 1.5, se = FALSE)
```






